### ISSUE TITLE
Update readme to include correct library name

### ISSUE THREAD

**Issue by 20BBrown14** [SelectQuoteLabs/SQHooks#24]
`npm i` is case sensitive and the README has `SQHooks` instead of `sqhooks` and could cause confusion for people trying to install the library. We should update it to be correct.

**Comment by SeanGroff** [comment]
This issue was addressed here https://github.com/SelectQuoteLabs/SQHooks/pull/35/files
The issue never closed because the PR didn't get linked to the issue.
Closing issue
