### ISSUE TITLE
useAutoHeight returns autoHeight as undefined

### ISSUE THREAD

**Issue by lucas-homer** [SelectQuoteLabs/SQHooks#37]
We're consuming this hook in SQFormScrollableCard, and when that component's prop `isSelfBounding` has the value `true`, we use the return value `autoHeight` from `useAutoHeight` and apply it to the container <div>'s height style. When we log the value of `autoHeight` when we consume it `SQFormScrollableCard`, however, it shows that it's `undefined`, which appears to be a bug. 

[loom video](https://www.loom.com/share/71ba9e4e0d6e4ce1afec2f47eac3051c)

**Comment by jamesgriffith9519** [comment]
I've been looking into this for a little bit today and this is what i've found so far. I believe it could be the issue but I'm not 100% yet, if anyone else is looking at this issue, let me know what you think!  https://www.loom.com/share/28ccd7af6d7e484b9204f27437c82ece

Additionally, it looks like the function useAuto height uses a ref to target the container that we want to autosize, and it seems like refs may not work in storybook, i base this on these issue pages:https://github.com/storybookjs/storybook/issues/10446 https://github.com/storybookjs/storybook/pull/15890
