### ISSUE TITLE
List of Hooks to live in SQHooks

### ISSUE THREAD

**Issue by SeanGroff** [SelectQuoteLabs/SQHooks#8]
- [x] useDialog
- [x] usePrevious **sc2-senior
- [x] useLocalStorage **useHooks.com
- [x] useIsomorphicLocalStorage **senior-external-qe-ui
- [x] useDropdownOptions ** sc2-senior
- [x] useClipboard **sc2-senior
- [x] useDebounce **Either expose `use-debounce` from npm or use the one on useHooks.com
- [x] useToggle **https://usehooks.com/useToggle/

Key:
** Repo hook currently lives in

**Comment by SeanGroff** [comment]
Not all hooks will live in this repo. If we have a shared component who's functionality won't work without the hook, then that hook should live with the shared component. Same with Form hooks, RQ hooks, API data fetching hooks, etc.

**Comment by SeanGroff** [comment]
Please comment with any hooks I've missed. There's probably quite a few 😬

**Comment by codyarose** [comment]
@SeanGroff I was looking for `useDropdownOptions` in sc2-senior, but I could only find `useDropdownFilter` - is that the same thing?

Also, `useClipboard` in sc2-senior includes a `toastr`, do we want to include that here as well or just the basic clipboard logic?

**Comment by SeanGroff** [comment]
> @SeanGroff I was looking for `useDropdownOptions` in sc2-senior, but I could only find `useDropdownFilter` - is that the same thing?
> 
> Also, `useClipboard` in sc2-senior includes a `toastr`, do we want to include that here as well or just the basic clipboard logic?

Great questions. 

useDropdownOptions - name was already taken so I made a hook called `useTransformToOptions`. Let's use the code from `useTransformToOptions` but name it `useDropdownOptions`. Sorry for the confusion.

useClipboard - Let's exclude the toastr since some projects use toastr, some snackbar, etc. Let's leave it up to the consumer to compose this hook with their own that could incorporate their notification.

**Comment by SeanGroff** [comment]
Big shoutout to @codyarose for migrating all the hooks from various repos to this library, as well as writing tests for each, adding Types to each hook, and writing brief documentation for each! 💯
